import os
import re
import subprocess
import setuptools

with open("README.md", encoding="utf-8") as f:
    long_description = f.read()

with open("autossh/__init__.py", encoding="utf-8") as f:
    version = re.search(r'^__version__\s*=\s*["\']([^"\']+)', f.read(), re.M).group(1)


def _capture_git(args):
    try:
        r = subprocess.run(["git"] + args, capture_output=True, text=True, timeout=2)
        return r.stdout.strip() if r.returncode == 0 else None
    except Exception:
        return None


def _capture_branch():
    """Find the most useful ref name for the current HEAD.

    Handles pip's git+url install case where HEAD may be left on the default
    branch (main/master) or detached after a checkout-by-commit, by falling
    back to any ref that points at HEAD and preferring non-default refs.
    """
    b = _capture_git(["symbolic-ref", "--short", "-q", "HEAD"])
    if b and b not in ("main", "master"):
        return b
    refs = _capture_git(["for-each-ref", "--points-at", "HEAD",
                         "--format=%(refname:short)",
                         "refs/heads/", "refs/remotes/"])
    if refs:
        all_refs = [r.strip() for r in refs.split("\n") if r.strip()]
        defaults = {"main", "master", "HEAD",
                    "origin", "origin/main", "origin/master", "origin/HEAD"}
        non_default = [r for r in all_refs if r not in defaults]
        if non_default:
            non_default.sort(key=lambda r: (r.startswith("origin/"), len(r)))
            return non_default[0]
        if all_refs:
            return all_refs[0]
    return b


# Embed git info into the package at build time, so pip-installed wheels
# still report commit/branch via `--version`. Overwritten on every build.
commit = _capture_git(["rev-parse", "--short", "HEAD"]) if os.path.isdir(".git") else None
branch = _capture_branch() if commit else None
with open("autossh/_build_info.py", "w", encoding="utf-8") as f:
    f.write("# Auto-generated by setup.py at build time. Do not edit or commit.\n")
    f.write(f"commit = {commit!r}\n")
    f.write(f"branch = {branch!r}\n")

setuptools.setup(
    name="autossh-cli",
    version=version,
    description="Auto-SSH toolkits with alias-based host management and password encryption",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/spgyip/autossh",
    author="supergui",
    author_email="supergui@live.cn",
    license="MIT",
    classifiers=[
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Operating System :: POSIX :: Linux",
        "Operating System :: MacOS",
        "Environment :: Console",
        "Topic :: System :: Networking",
        "Topic :: Utilities",
    ],
    python_requires=">=3.8",
    install_requires=["pexpect", "pyyaml", "cryptography"],
    packages=setuptools.find_packages(),
    entry_points={
        "console_scripts": [
            "assh    = autossh.cli.assh:main",
            "apush   = autossh.cli.apush:main",
            "apull   = autossh.cli.apull:main",
            "acat    = autossh.cli.acat:main",
            "aedit   = autossh.cli.aedit:main",
            "amaster = autossh.cli.amaster:main",
        ],
    },
    include_package_data=True,
    zip_safe=False,
)
